app = "toyota-hacks-blog"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[scale]
  count = 1

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
